"""empty message

Revision ID: 4907514cbe6f
Revises: 
Create Date: 2021-09-27 18:01:42.354807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4907514cbe6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drosher', sa.Column('status', sa.Integer(), server_default="0", nullable=False))
    op.drop_column('user', 'image_file')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image_file', sa.VARCHAR(length=20), nullable=False))
    op.drop_column('drosher', 'status')
    # ### end Alembic commands ###
