"""empty message

Revision ID: 9a35cdc301a9
Revises: 4907514cbe6f
Create Date: 2021-09-28 17:54:35.580742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a35cdc301a9'
down_revision = '4907514cbe6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('load', sa.Column('active', sa.Boolean(), server_defualt="True", nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('load', 'active')
    # ### end Alembic commands ###
